import type { NextPage } from 'next'
import Head from 'next/head'
import BlankLayout from '../components/BlankLayout'
import DashboardLayout from '../components/DashboardLayout'
import { NextPageWithLayout } from '../types/global'

const Home: NextPageWithLayout = () => {
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"h-full"}>
        x
      </main>


    </div>
  )
}

Home.getLayout = (page) => {
  return <DashboardLayout>{page}</DashboardLayout>
}

export default Home
